application:
  subdomain: clewdr
  background_task: true
  public_path:
    - /
  routes:
    - /=http://clewdr:8484/
services:
  clewdr:
    # upstream: ghcr.io/xerxes-2/clewdr:v0.12.26
    image: registry.lazycat.cloud/czyt/xerxes-2/clewdr:a4181563ba2dac92
    environment:
      - CLEWDR_ADMIN_PASSWORD="{{ .U.clewdr_admin_password }}"
      - CLEWDR_PASSWORD="{{ .U.clewdr_api_key }}"
      - CLEWDR_COOKIE_ARRAY=[{{ .U.claude_session_keys }}]
      - CLEWDR_GEMINI_KEYS=[{{ .U.gemini_api_keys }}]
      - CLEWDR_MAX_RETRIES=10
      - CLEWDR_CACHE_RESPONSE=0
